### ISSUE TITLE
termbox library panic

### ISSUE THREAD

**Issue by iwittkau** [iwittkau/ssh-select#19]
Sometimes `sshs` crashes with the following runtime panic:

```
panic: runtime error: slice bounds out of range

goroutine 40 [running]:
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/iwittkau/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20180819125858-b66b20ab708e/api.go:348 +0x91e
github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc0000e2240)
	/Users/iwittkau/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:354 +0x30
created by github.com/jroimartin/gocui.(*Gui).MainLoop
	/Users/iwittkau/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:352 +0x57
```

**Comment by iwittkau** [comment]
Looks like `termbox-go` AND `gocui` are not actively maintained anymore. 
We should try to move to [tcell](https://github.com/gdamore/tcell) which conveniently has a termbox compatibility package.
